### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by Florvis** [smadds/node-red-contrib-udmx#5]
Hi

I'm using this usb - dmx cable : https://www.steinigke.de/en/mpn51860118-eurolite-usb-dmx512-interface-update-adaptor.html

First I had troubles installing the node, but after folowing the instructions on https://github.com/tessel/node-usb#readme 
I was able to install the node.

But now, I've tried restaring node-red, and also my raspberry pi, but node-red doesn't find my device, is there maybe something I still have to do?

Thanks in advance for the help.

**Comment by Florvis** [comment]
![image](https://user-images.githubusercontent.com/6705665/50928624-7809d300-145b-11e9-9050-beeb04e1d1d2.png)

This is de device id of my dongle, it's not the same as the one you are looking for, did I do something wrong with the installation, or is this not a good dongle?

**Comment by smadds** [comment]
Your device is not the same as the one this node is written for. If I do a lsusb of my server this is what I get:
<img width="534" alt="udmx_lsusb" src="https://user-images.githubusercontent.com/5259870/50934938-29ac0280-1462-11e9-8d56-3f554e942847.PNG">

If you want the node to recognise your device you need to edit line 7 in udmx.js to the USB ID of your device. Change it from
`var udev = usb.findByIds(0x16c0, 0x5dc);`
to
`var udev = usb.findByIds(0x0403, 0x6001);`

I can't guarantee it will work in the same way, but at least it will recognise the USB device.

**Comment by Florvis** [comment]
Hi

Thanks for the quick response. I'll try that later today.
If that would not work, do you have a link were I could order the same device as you have?

KR
Floris

**Comment by smadds** [comment]
If you search ebay, amazon or aliexpress for usb dmx or udmx you'll see plenty. Some examples:-

- https://www.ebay.co.uk/itm/PC-Satge-USB-to-DMX-Lighting-Computer-Controller-Dimmer-Interface-Adapter-DMX512/323561358462
- https://www.amazon.co.uk/Enyu-Lighting-Controller-Interface-Computer/dp/B07KKGJLGF
- https://www.aliexpress.com/item/Lixada-USB-to-DMX-Interface-Adapter-LED-DMX512-Computer-PC-Stage-Lighting-Controller-Dimmer/32793890146.html

**Comment by Florvis** [comment]
Hi

Thanks, for the links.
I changed the code in udmx.js as you said, but I stil get the "not found" feedback.

**Comment by ozett** [comment]
![nanodmx](https://user-images.githubusercontent.com/5937811/52663024-f39ceb00-2f05-11e9-91f9-dfaed857932f.png)


i did it like you advised, changed the vendor-id and product-id for my nano-dmx usb-dongle and it showed: connected.

thankx,
i will now test if it is working...

**Comment by ozett** [comment]
```
12 Feb 20:40:21 - [error] [udmx:ae2ad85f.494a98] Error: LIBUSB_TRANSFER_STALL
12 Feb 20:40:21 - [red] Uncaught Exception:
12 Feb 20:40:21 - TypeError: this.status is not a function
    at Device.<anonymous> (/home/olaf/.node-red/node_modules/node-red-contrib-udmx/udmx.js:19:25)
    at Transfer.<anonymous> (/home/olaf/.node-red/node_modules/usb/usb.js:133:15)
```

:crying_cat_face: 

![nano-error](https://user-images.githubusercontent.com/5937811/52663461-fba95a80-2f06-11e9-9b7f-70a8b60dcc2b.png)


the end...

**Comment by NickvanZon** [comment]
> f you want the node to recognise your device you need to edit line 7 in udmx.js to the USB ID of your device. Change it from
> `var udev = usb.findByIds(0x16c0, 0x5dc);`
> to
> `var udev = usb.findByIds(0x0403, 0x6001);`
> 
> I can't guarantee it will work in the same way, but at least it will recognise the USB device.

how do i change the udmx.js?

**Comment by PizzaProgram** [comment]
> how do i change the udmx.js?

Dear @NickvanZon ,

1. You need to locate your `.node-red` directory. On linux tipically :  
  `/home/YOUR_USER_NAME/.node-red/node_modules/node-red-contrib-udmx`
2. make a copy from the `udmx.js` file first,
3.  edit it, 
4. save it back to that directory, overwrite old one
4. restart node-red. (In the terminal, type: `sudo node-red-stop` , than `sudo node-red-start`)
5. reload the page in the browser [F5], or even click Deploy FULL.

**Comment by McBene** [comment]
Thanks for your instructions. It seems to work. 
But I can´t see any output at the DMX Port of The USB-Gateway. 
At node-red it looks like (Screenshot).
Can i get any diagnostic for the Node?

![image](https://user-images.githubusercontent.com/99618526/153775526-6ad22f10-6910-450f-8419-db2671497e03.png)

**Comment by smadds** [comment]
Are you using this under Linux? Maybe try the lsusb command to find the id of your device?

**Comment by ozett** [comment]
> Can i get any diagnostic for the Node?

there is a log output: node-red-log
https://nodered.org/docs/user-guide/runtime/logging

**Comment by McBene** [comment]
Yes, using Linux at a Raspberry Pi4 : 
![image](https://user-images.githubusercontent.com/99618526/153888352-eb83eee9-d842-4ba3-964e-c7f21138567f.png)
Here is the lsusb:
![image](https://user-images.githubusercontent.com/99618526/153888659-b7eafc1a-3275-4eb9-b037-4332af26fe8b.png)
![image](https://user-images.githubusercontent.com/99618526/153889827-10283d5e-7172-4a4b-bd1d-79cd06fe5a9a.png)

Before the change from 0x16c0, 0x5dc to 0x0403, 0x6001 the Node show not the state "connect" or "CH001:219"

**Comment by proffalken** [comment]
FWIW, I'm getting close to an answer for this running in Docker at https://www.reddit.com/r/AlpineLinux/comments/165t1th/running_mdev_s_to_scan_for_devices_on_container/

I'm wondering if a config box could be created to allow for input of the device/vendor ID in future as many of the USB dongles from Amazon etc appear to be the `0x0403, 0x6001` variants these days rather than the original intended.

Better yet, the ability to select from a drop-down of plugged-in USB devices would be fantastic!

**Comment by christophengelmayer** [comment]
The USB Dongle you are using (Manufacturer: FTDI) is not compatible with the uDMX driver.
Instead you have to use the OpenDMX driver to "talk" to that device.

Try the https://github.com/node-dmx/dmx package, especially the [enttec-open-usb-dmx.js](https://github.com/node-dmx/dmx/blob/master/drivers/enttec-open-usb-dmx.js) driver.

```
const DMX = require('dmx');
const dmx = new DMX();
const universe = dmx.addUniverse('demo', 'enttec-open-usb-dmx', '/dev/tty.usbserial-A50285BI');

universe.updateAll(255);
```
(Replace `/dev/tty.usbserial-A50285BI` with your device mountpoint.)

I am not aware of any node-red node that supports the OpenDMX driver out of the box. You could use the code above to get started and write your own.

**Comment by proffalken** [comment]
Amazing, thanks @christophengelmayer !

**Comment by proffalken** [comment]
FWIW I worked around this by switching from Docker to a raspberry Pi, installing [OLA](https://wiki.openlighting.org/index.php/Open_Lighting_Project) from the standard APT repositories, enabling USB FTDI in the OLA config and then using [NodeRed OLA](https://flows.nodered.org/node/node-red-contrib-ola) to send messages to the OLA server.

This isn't as "nice" as being able to talk directly to my cheap chinese USB DMX dongle, but it is working well, so I figured I'd put this here in case someone who also has a cheap chinese dongle tries to use nodered uDMX.

**Comment by christophengelmayer** [comment]
@proffalken Thanks for your update. How is the "performance" using OLA with the USB FTDI Stick?

[My solution](https://github.com/smadds/node-red-contrib-udmx/issues/5#issuecomment-1700459018) works but it is only capable of updating DMX values at about 30 times/second.
If I fade a light from 0 to 255 in 500ms it "stutters" a little bit.


I'm wondering if the 30Hz limit comes from the FTDI-Stick or the driver?
@proffalken Have you tried fading lights? How is your performance?

**Comment by proffalken** [comment]
@christophengelmayer - I only got it working this morning, and haven't tried more than alternating colours once a second so far.

I'll try the gradient stuff later on today if I get a chance - my goal is to use this to react to messages on an MQTT bus and change the lights accordingly for an Escape Room-style setup.

**Comment by proffalken** [comment]
@christophengelmayer try the below, there's a delay of just 5ms between steps and my cheap chinese light seems to fade up without jitter:

```json
[
    {
        "id": "9c99abb435339285",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "78cb4b068737cc2c",
        "type": "function",
        "z": "9c99abb435339285",
        "name": "Fade",
        "func": "var colour = [0,0,0];\nvar brightness = 0;\nvar total_fade_length = 1;\nvar step_size = 1;\n\nfunction sleep(ms) {\n    return new Promise(resolve => setTimeout(resolve, ms));\n}\n\nif (msg.payload.total_fade_length){\n    total_fade_length = msg.payload.total_fade_length;\n    node.warn(\"Fade length set to \" + total_fade_length + \"based on message\");\n}\n\nif (msg.payload.colour){\n    colour = msg.payload.colour;\n}\n\nstep_size = 255 / total_fade_length;\n\nnode.warn(step_size);\n\nfor (let seconds_passed = 0; seconds_passed < total_fade_length; seconds_passed++) {\n  brightness = brightness + step_size;\n  msg.payload = {\n    \"channels\":[ {\n            \"channel\": 13,\n            \"value\": brightness,\n        },\n        {\n            \"channel\": 14,\n            \"value\": colour[0],\n        },\n        {\n            \"channel\": 15,\n            \"value\": colour[1],\n        },\n        {\n            \"channel\": 16,\n            \"value\": colour[2],\n        }\n        ]\n    };\n    node.send(msg);\n    await sleep(5);\n}\nreturn;",
        "outputs": 1,
        "timeout": 0,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 990,
        "y": 500,
        "wires": [
            [
                "93075025a6189a9a",
                "360b821f24d7d0df"
            ]
        ]
    },
    {
        "id": "93075025a6189a9a",
        "type": "debug",
        "z": "9c99abb435339285",
        "name": "Payload",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 1380,
        "y": 420,
        "wires": []
    },
    {
        "id": "637d47e8196ba65e",
        "type": "inject",
        "z": "9c99abb435339285",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"colour\":[123,0,123],\"total_fade_length\":255}",
        "payloadType": "json",
        "x": 750,
        "y": 500,
        "wires": [
            [
                "78cb4b068737cc2c"
            ]
        ]
    },
    {
        "id": "360b821f24d7d0df",
        "type": "ola",
        "z": "9c99abb435339285",
        "name": "",
        "host": "127.0.0.1",
        "port": 9090,
        "universe": 1,
        "size": 512,
        "x": 1370,
        "y": 520,
        "wires": []
    }
]
```
